upstream user_service {
    server user-service:8080;
}

upstream hotel_service {
    server hotel-service:8000;
}

server {

    listen 80;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log debug;

    location /api/users/ {
        proxy_pass http://user_service;
    }

    location /api/bookings {
        proxy_pass http://hotel_service;
    }

    location /api/search/ {
        proxy_pass http://hotel_service;
    }
}
