spring.application.name=app
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=ERROR
logging.level.org.mongodb.driver.cluster=ERROR
logging.level.org.mongodb.driver.connection=ERROR
